apiVersion: v1
kind: ConfigMap
metadata:
  name: dmm-config
  namespace: dmm
data:
  DB_NAME_DMM: "aavana_dmm"
  DMM_CORS_ORIGINS: "https://dmm.aavanagreens.in,https://campaign-manager-28.preview.emergentagent.com"